// packages/shared-types/index.ts

/**
 * The payload sent from the Electron Client to the Server during setup.
 */
export interface SetupTrackerPayload {
  targetUrl: string;
  userIntent: string;           // e.g., "Notify me when price drops below 2000"
  sanitizedHtml: string;        // Pruned HTML DOM tree
  interceptedXhrJson?: string;  // Stringified JSON from background API calls (if any)
  highlightedElement: {
    textContent: string;
    tagName: string;
    className?: string;
  };
}

/**
 * The deterministic rule generated by Gemini (The "God Call" output).
 */
export interface ExtractionRule {
  extractionType: 'jsonpath' | 'xpath';
  rule: string;                 // e.g., "$.products[0].price" or "//div[@class='price']"
  operator: '<' | '>' | '==' | 'contains';
  targetValue: string | number;
  validationAnchorXpath: string; // Used for the Self-Healing check
}

/**
 * The final Job object saved to the Database and processed by BullMQ.
 */
export interface TrackerJob {
  id: string;
  userId: string;
  targetUrl: string;
  rule: ExtractionRule;
  status: 'active' | 'paused' | 'error';
  lastCheckedAt?: Date;
}